"""
Use this Snakefile to collect DCV and CrPV mutations
and filter them.
"""

rule all:
    input:
        "results_summary/all_mutations.annotated.filtered.csv",
        "results_summary/all_mutations.filtered.csv",
        "results_summary/coverage.csv",
        "results_summary/all_snpgenie_codon_results.csv",
        "results_summary/all_snpgenie_population_summary.csv",
        "results_summary/all_snpgenie_product_results.csv",
        "results_summary/all_snpgenie_site_results.csv",
    default_target: True

rule filter_and_merge_mutations:
    input:
        fnames_csv=["results/crpv_all_mutations.no_parental.csv", ]
    output:
        fname_out="results_summary/all_mutations.filtered.old.csv",
    conda:
        "envs/annotate_vcf.yaml"
    script:
        "scripts/filter_and_merge_mutations.py"

rule collect_snpgenie_codon:
    input:
        fname_codon_crpv=f"results/crpv_snpgenie_codon_results.csv",
        fname_population_summary_crpv=f"results/crpv_snpgenie_population_summary.csv",
        fname_product_results_crpv=f"results/crpv_snpgenie_product_results.csv",
        fname_site_results_crpv=f"results/crpv_snpgenie_site_results.csv",
        fname_codon_dcv=f"results/dcv_snpgenie_codon_results.csv",
        fname_population_summary_dcv=f"results/dcv_snpgenie_population_summary.csv",
        fname_product_results_dcv=f"results/dcv_snpgenie_product_results.csv",
        fname_site_results_dcv=f"results/dcv_snpgenie_site_results.csv",
    output:
        fname_codon=f"results_summary/all_snpgenie_codon_results.csv",
        fname_population_summary=f"results_summary/all_snpgenie_population_summary.csv",
        fname_product_results=f"results_summary/all_snpgenie_product_results.csv",
        fname_site_results=f"results_summary/all_snpgenie_site_results.csv",
    run:
        import pandas as pd

        df_dcv = pd.read_csv(input.fname_codon_dcv)
        df_dcv['virus'] = 'DCV'
        df_crpv = pd.read_csv(input.fname_codon_crpv)
        df_crpv['virus'] = 'CrPV'
        pd.concat([df_dcv, df_crpv]).to_csv(output.fname_codon)

        df_dcv = pd.read_csv(input.fname_population_summary_dcv)
        df_dcv['virus'] = 'DCV'
        df_crpv = pd.read_csv(input.fname_population_summary_crpv)
        df_crpv['virus'] = 'CrPV'
        pd.concat([df_dcv, df_crpv]).to_csv(output.fname_population_summary)

        df_dcv = pd.read_csv(input.fname_product_results_dcv)
        df_dcv['virus'] = 'DCV'
        df_crpv = pd.read_csv(input.fname_product_results_crpv)
        df_crpv['virus'] = 'CrPV'
        pd.concat([df_dcv, df_crpv]).to_csv(output.fname_product_results)

        df_dcv = pd.read_csv(input.fname_site_results_dcv)
        df_dcv['virus'] = 'DCV'
        df_crpv = pd.read_csv(input.fname_site_results_crpv)
        df_crpv['virus'] = 'CrPV'
        pd.concat([df_dcv, df_crpv]).to_csv(output.fname_site_results)



rule filter_and_merge_mutations_annotated:
    input:
        fname_crpv="results/crpv_all_mutations.annotated.no_parental.csv",
        fname_dcv="results/dcv_all_mutations.annotated.csv", # includes correct parental (wrt to parental consensus)
        fname_crpv_p0="results/crpv_all_mutations.annotated.csv",]
    output:
        fname_out="results_summary/all_mutations.annotated.filtered.csv",
    conda:
        "envs/annotate_vcf.yaml"
    script:
        "scripts/filter_and_merge_mutations.annotated.py"

rule filter_and_merge_mutations:
    input:
        fname_crpv="results/crpv_all_mutations.no_parental.csv",
        fname_dcv="results/dcv_all_mutations.csv", # includes correct parental (wrt to parental consensus)
        fname_crpv_p0="results/crpv_all_mutations.csv",]
    output:
        fname_out="results_summary/all_mutations.filtered.csv",
    conda:
        "envs/annotate_vcf.yaml"
    script:
        "scripts/filter_and_merge_mutations.py"

rule coverage_summary:
    input:
        fname_dcv="results/dcv_coverage.csv",
        fname_crpv="results/crpv_coverage.csv",
    output:
        fname_out="results_summary/coverage.csv",
    conda:
        "envs/annotate_vcf.yaml"
    script:
        "scripts/coverage_summary.py"
